Update build_with_verify.yml

diff --git a/.github/workflows/build_with_verify.yml b/.github/workflows/build_with_verify.yml
--- a/.github/workflows/build_with_verify.yml
+++ b/.github/workflows/build_with_verify.yml
@@ -10,6 +10,14 @@ jobs:
       run:  | 
         sudo apt-get install jq
         jq
+        tmp=0
+        if [ "$result" -ne "0" ]
+        then 
+          echo "Package integrity error."
+          exit 1
+        else
+          echo "Package integrity validated successully."
+        fi
 
     - name: install valint
       run: | 
@@ -40,7 +48,7 @@ jobs:
         if [ "$result" -ne "0" ]
         then 
           echo "Package integrity error."
-          exit(1)
+          exit 1
         else
           echo "Package integrity validated successully."
         fi
